### ISSUE TITLE
required positional argument: 'name'

### ISSUE THREAD

**Issue by Awais9** [bentoml/gallery#11]
I am new to this topic and exploring the example. By following all the instructions I am facing following issue:
Traceback (most recent call last):
  File "/Users/awais/Python_Projects/TextClasificationTest/import_service.py", line 10, in <module>
    **bento_svc = serviceClass.pack(model=model,word_index=word_index)**
TypeError: pack() missing 1 required positional argument: 'name'
where is this missing argument 'name' and from where it has to pass? Please guide me on it. Thanks

**Comment by parano** [comment]
hi, looks like we made a breaking change a few versions back to the `pack` method and that example is broken now.

The right way to do pack now is:
```
bento_svc = serviceClass()
bento_svc.pack('model', model)
bento_svc.pack('word_index', word_index)
bento_svc.save()
```

We will update those example notebooks soon, thanks for reporting the issue!

**Comment by Awais9** [comment]
Thanks for guidance. Let me try with it and will get back.

**Comment by Awais9** [comment]
<img width="484" alt="Screenshot 2020-01-15 at 11 18 32 AM" src="https://user-images.githubusercontent.com/37929195/72409905-dfeaac00-3788-11ea-9f6e-8c50d1d8492a.png">
Please check the screenshot. **serviceClass()** is not callable

**Comment by Awais9** [comment]
Yes! it is working now. Thanks
