### ISSUE TITLE
Most of the notebooks on colab are not found

### ISSUE THREAD

**Issue by amir78pgd** [bentoml/gallery#117]
https://docs.bentoml.org/en/0.13-lts/examples.html

**Comment by parano** [comment]
Thanks @amir78pgd - just submitted a PR to fix the links, they should be pointing to the 0.13-LTS branch now.

In the meanwhile, you should be able to visit the notebooks from the gallery repo's readme in 0.13-LTS branch: https://github.com/bentoml/gallery/tree/0.13-LTS
